api/urls.py
from django.conf.urls import url

from api import views


urlpatterns = [
    url(r'^projects/$', views.get_projects),
    url(r'^session/$', views.get_last_session),
    url(r'^start/(?P<id>\d+)/$', views.start_task),
    url(r'^create/$', views.create_task),
    url(r'^update/(?P<id>\d+)/$', views.update_task),
    url(r'^stop/(?P<id>\d+)/$', views.stop_task),
    url(r'^login/$', views.login),
]

timer/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

#from tasks import views as task_views
from core import views as core_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/$', core_views.dash, name='profile'),
    url(r'^accounts/logout/$',
        auth_views.logout,
        {'next_page': '/accounts/login/'},
        name='logout'),
    url(r'^accounts/login/$',
        auth_views.login,
        {'template_name': 'core/pages-login.html'},
        name='login'),
    url(r'^register/$', core_views.registration, name='registration'),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('profile'))),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

core/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User


class RegistrationForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)
    pwd2 = forms.CharField(max_length=50, widget=forms.PasswordInput)

    def clean_email(self):
        if 'email' in self.cleaned_data:
            if User.objects.filter(email=self.cleaned_data['email']):
                raise forms.ValidationError('This email is already in use')
            return self.cleaned_data['email']

    def clean(self):
        if 'password' in self.cleaned_data and 'pwd2' in self.cleaned_data:
            if self.cleaned_data['password'] != self.cleaned_data['pwd2']:
                raise forms.ValidationError("The passwords don't match")
            return self.cleaned_data


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)

    def clean(self):
        if 'username' in self.cleaned_data and 'password' in self.cleaned_data:
            username = self.cleaned_data['username']
            password = self.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError(
                    'Please enter a valid username/password')
            if not user.is_active:
                raise forms.ValidationError(
                    'You are not allowed to login.\
                    Please contact your administrator')
            self.cleaned_data['user'] = user
            return self.cleaned_data

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from core.forms import LoginForm, RegistrationForm
from tasks.models import Project, Task, TaskSession, Member


def registration(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            login_user(request, name, email, password)
            return redirect('profile')
    else:
        form = RegistrationForm()
    return render(request, 'core/registration.html', {'form': form})


def login_user(request, name, email, password):
    try:
        user = User.objects.get(username=email)
        user.set_password(password)
        user.save()
    except User.DoesNotExist:
        user = User.objects.create_user(email, email=email, password=password)
        user.first_name = name
        user.save()
    usr = authenticate(username=email, password=password)
    login(request, usr)


@login_required
def dash(request):
    projects = Project.objects.filter(project_members__user=request.user)
    task_count = Task.objects.filter(member__user=request.user).count()

    start = timezone.now().replace(day=1, hour=0, minute=0, second=0)
    total_seconds = sum([sess.duration for sess in TaskSession.objects.filter(
        task__member__user=request.user, started__gte=start)])
    return render(
        request,
        'core/dash.html',
        {
            'projects': projects,
            'task_count': task_count,
            'total_hours': total_seconds / 3600.
        })

templates/core/add_topic.html
{% extends 'core/profile.html' %}
{% load static from staticfiles %}

{% block pagetitle %}New Topic{% endblock pagetitle %}

{% block extra-js %}
<script type="text/javascript">
    $(function(){
        $('#id_name').attr('class', 'form-control');
        $('#id_post').attr('class', 'form-control');
    });
        </script>
{% endblock extra-js %}

{% block breadcrumb %}
<ul class="breadcrumb">
    <li><a href="{% url 'profile' %}">Conversations</a></li>
    <li class="active">New Topic</li>
</ul>
{% endblock breadcrumb %}

{% block midpanel-heading %}
    <h3 class="panel-title">Start New Topic</h3>
{% endblock midpanel-heading %}

{% block midpanel-body %}
<form action="" class="form-horizontal" method="post">{% csrf_token %}
<div class="form-group{% if form.name.errors %} has-error{% endif %}">
    <label class="control-label col-md-2 col-xs-12">Topic</label>
    <div class="col-md-8 col-xs-12">
        {% if form.name.errors %}
             <label class="control-label">{{ form.name.errors }}</label>
        {% endif %}
        {{ form.name }}
    </div>
</div>

<div class="form-group{% if form.post.errors %} has-error{% endif %}">
    <label class="control-label col-md-2 col-xs-12">Post</label>
    <div class="col-md-8 col-xs-12">
        {% if form.post.errors %}
             <label class="control-label">{{ form.post.errors }}</label>
        {% endif %}
        {{ form.post }}
    </div>
</div>
<div class="form-group">
    <div class="col-md-2"></div>
    <div class="col-md-6">
        <button class="btn btn-block btn-primary">Post</button>
    </div>
</div>
</form>
{% endblock midpanel-body %}

{% block midpanel-footer %}
{% endblock midpanel-footer %}

templates/core/base.html
{% load static from staticfiles %}
<!DOCTYPE html>

<html lang="en" class="body-full-height">
    <head>        
    {% block head %}
      {% block title %}
        <title>Task Timer</title>            
      {% endblock title %}
      {% block meta %}
        <!-- META SECTION -->
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <link rel="icon" href="favicon.ico" type="image/x-icon" />
        <!-- END META SECTION -->
      {% endblock meta %}
      {% block extra-meta %}{% endblock extra-meta %}
        
      {% block js %}
        <!-- JS INCLUDE -->
        <script src="{% static 'js/plugins/jquery/jquery.min.js' %}"></script>
        <!-- END JS INCLUDE -->
      {% endblock js %}
      {% block extra-js %}{% endblock extra-js %}
      {% block header-js %}{% endblock header-js %}
      {% block extra-header-js %}{% endblock extra-header-js %}
      {% block css %}
        <!-- CSS INCLUDE -->        
        <link rel="stylesheet" type="text/css" id="theme" href="{% static 'css/theme-forest.css' %}"/>
        <!-- EOF CSS INCLUDE -->    
        {% endblock css %}
    {% endblock head %}
    {% block extra-head %}{% endblock extra-head %}
    </head>
    <body>
    {% block body %}
        
        <div class="login-container lightmode">
        
            <div class="login-box animated fadeInDown">
                {% block quote %}{% endblock %}
                <div class="login-logo"></div>
                <div class="login-body">
                    {% block innerbody %}
                    <div class="login-title"><strong>Log In</strong> to your account</div>
                    {% endblock innerbody %}
                </div>
                <div class="login-footer">
                    <div class="pull-left">
                        &copy; 2017 Clear Code Software Labs
                    </div>
                    <div class="pull-right">
                        <a href="#">About</a> |
                        <a href="#">Privacy</a> |
                        <a href="#">Contact Us</a>
                    </div>
                </div>
            </div>
            
        </div>
        
    {% endblock body %}
    </body>
</html>

templates/core/dash.html
{% extends 'tasks/form_base.html' %}
{% load static from staticfiles %}

{% block pagetitle %}Payment History{% endblock pagetitle %}

	{% block breadcrumb %}
    <!-- START BREADCRUMB -->
    <ul class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li><a href="{% url 'profile' %}">Projects</a></li>
        <li class="active">Welcome</li>
    </ul>
    <!-- END BREADCRUMB -->
	{% endblock breadcrumb %}
	

{% block pagecontent %}
 <!-- PAGE CONTENT WRAPPER -->
    <div class="page-content-wrap">                
       <!-- START WIDGETS -->                    
       <div class="row">
           <div class="col-md-3">
               <div class="widget widget-default widget-item-icon">
                   <div class="widget-item-left">
                       <span class="fa fa-user"></span>
                   </div>                             
                   <div class="widget-data">
                       <div class="widget-int num-count">Hi {{ user.first_name }}</div>
                       <div class="widget-title"> {{total_hours|floatformat:2}} hours</div>
                       <div class="widget-subtitle">completed this month</div>
                   </div>      
                   <div class="widget-controls">                                
                       <a href="#" class="widget-control-right widget-remove" data-toggle="tooltip" data-placement="top" title="Remove Widget"><span class="fa fa-times"></span></a>
                   </div>
               </div>                   
               <!-- START WIDGET SLIDER -->
                {% comment %}  
               <div class="widget widget-default widget-carousel">
                   
                   <div class="owl-carousel" id="owl-example">
                       <div>                                    
                           <div class="widget-title">Last Payment</div>                                                                        
                           <div class="widget-subtitle">27/12/2015 15:23</div>
                           <div class="widget-int">N13,548.00</div>
                       </div>
                       <div>                                    
                           <div class="widget-title">Early Payment</div>
                           <div class="widget-subtitle">14 (out of 16)</div>
                           <div class="widget-int">87.6%</div>
                       </div>
                       <div>                                    
                           <div class="widget-title">Next Payment</div>
                           <div class="widget-subtitle">(Due date)</div>
                           <div class="widget-int">27/01/2016</div>
                       </div>
                   </div>                            
                   <div class="widget-controls">                                
                       <a href="#" class="widget-control-right widget-remove" data-toggle="tooltip" data-placement="top" title="Remove Widget"><span class="fa fa-times"></span></a>
                   </div>                           
                   
                   
               </div>        
               {% endcomment %}   
               <!-- END WIDGET SLIDER -->
               
           </div>
           <div class="col-md-3">
               
               <!-- START WIDGET MESSAGES -->
               <div class="widget widget-default widget-item-icon">
                   <div class="widget-item-left">
                       <span class="fa fa-book"></span>
                   </div>                             
                   <div class="widget-data">
                       <div class="widget-int num-count">{{ projects|length }}</div>
                       <div class="widget-title"> Projects</div>
                       <div class="widget-subtitle">active projects</div>
                   </div>      
                   <div class="widget-controls">                                
                       <a href="#" class="widget-control-right widget-remove" data-toggle="tooltip" data-placement="top" title="Remove Widget"><span class="fa fa-times"></span></a>
                   </div>
               </div>                            
               <!-- END WIDGET MESSAGES -->
               
           </div>
           <div class="col-md-3">
               <!-- START WIDGET REGISTRED -->
               <div class="widget widget-default widget-item-icon">
                   <div class="widget-item-left">
                       <span class="fa fa-tasks"></span>
                   </div>
                   <div class="widget-data">
                       <div class="widget-int num-count">{{ task_count }}</div>
                       <div class="widget-title">Tasks</div>
                       <div class="widget-subtitle">completed tasks</div>
                   </div>
                   <div class="widget-controls">                                
                       <a href="#" class="widget-control-right widget-remove" data-toggle="tooltip" data-placement="top" title="Remove Widget"><span class="fa fa-times"></span></a>
                   </div>                            
               </div>                            
               <!-- END WIDGET REGISTRED -->
              
           </div>
           <div class="col-md-3">
               
               <!-- START WIDGET CLOCK -->
               <div class="widget widget-danger widget-padding-sm">
                   <div class="widget-big-int plugin-clock">00:00</div>                            
                   <div class="widget-subtitle plugin-date">Loading...</div>
                   <div class="widget-controls">                                
                       <a href="#" class="widget-control-right widget-remove" data-toggle="tooltip" data-placement="left" title="Remove Widget"><span class="fa fa-times"></span></a>
                   </div>                            
                   <div class="widget-buttons widget-c3">
                       <div class="col">
                           <a href="#"><span class="fa fa-clock-o"></span></a>
                       </div>
                       <div class="col">
                           <a href="#"><span class="fa fa-bell"></span></a>
                       </div>
                       <div class="col">
                           <a href="#"><span class="fa fa-calendar"></span></a>
                       </div>
                   </div>                            
               </div>                        
               <!-- END WIDGET CLOCK -->
               
           </div>
       </div>
       <!-- END WIDGETS -->  
	   
       <div class="row">
           <div class="col-md-12">

               <!-- START LINE CHART -->
                <!-- START BASIC TABLE SAMPLE -->
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title">Projects</h3>
                                </div>
                                <div class="panel-body">
                                    <div class="table-responsive">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>Name</th>
                                                    <th>Start date</th>
                                                    <th># members</th>
                                                    <th>Last update</th>
                                                    <th># Tasks</th>
                                                    
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for project in projects %}
                                                <tr>
                                                    <td><a href="{% url 'task_list' id=project.id %}">{{ project.name }}</a></td>
                                                    <td>{{ project.started }}</td>
                                                    <td>{{ project.member_count }}</td>
                                                    <td>N/A</td>
                                                    <td>{{ project.task_count }}</td>                                                    
                                                </tr>
                                                {% endfor %}
                                              
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
               <!-- END LINE CHART -->

           </div>
	   </div>
    </div>
 <!-- PAGE CONTENT WRAPPER -->   
{% endblock pagecontent %}                             
            
      
   
	
	{% block extra-footer-js %}
	
    <!-- START THIS PAGE PLUGINS-->        
    <script type="text/javascript" src="{% static 'js/plugins/icheck/icheck.min.js' %}"></script>        
    <script type="text/javascript" src="{% static 'js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/scrolltotop/scrolltopcontrol.js' %}"></script>
    
    <script type="text/javascript" src="{% static 'js/plugins/morris/raphael-min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/morris/morris.min.js' %}"></script>       
    <script type="text/javascript" src="{% static 'js/plugins/rickshaw/d3.v3.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/rickshaw/rickshaw.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>                
    <script type="text/javascript" src="{% static 'js/plugins/bootstrap/bootstrap-datepicker.js' %}"></script>                
    <script type="text/javascript" src="{% static 'js/plugins/owl/owl.carousel.min.js' %}"></script>                 
    
    <script type="text/javascript" src="{% static 'js/plugins/moment.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/daterangepicker/daterangepicker.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/dash_chart.js' %}"></script>
    <!-- END THIS PAGE PLUGINS-->
	   
	{% endblock extra-footer-js %}

templates/core/home.html
{% extends "core/base.html" %}
{% load static from staticfiles %}

{% block extra-js %}
        <script type="text/javascript">
        $(function(){
                $('#id_username').attr('placeholder', 'E-mail');
                $('#id_username').attr('class', 'form-control');
                $('#id_password').attr('placeholder', 'Password');
                $('#id_password').attr('class', 'form-control');
        });
        </script>
{% endblock extra-js %}

{% block quote %}
   <div class="blockquote">
       <h4>"If there is no struggle there is no progress... Power concedes nothing without a demand. It never did and it never will.” 
           <footer><cite>Frederick Douglass</cite></footer>
       </h4>
   </div>
{% endblock %}

                    {% block innerbody %}
                    {% if form.non_field_errors %}
                    <div class="form-group has-error">
                        <label class="control-label">{{ form.non_field_errors }}</label>
                    </div>
                    {% endif %}
                    <div class="login-title"><strong>Log In</strong> to your account</div>
                    <form action="" class="form-horizontal" method="post">{% csrf_token %}
                    <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                        <div class="col-md-12">
                            {% if form.username.errors %}
                              <label class="control-label">{{ form.username.errors }}</label>
                            {% endif %}
                            {{ form.username }}
                        </div>
                    </div>
                    <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                        <div class="col-md-12">
                            {% if form.password.errors %}
                              <label class="control-label">{{ form.password.errors }}</label>
                            {% endif %}
                            {{ form.password }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <a href="#" class="btn btn-link btn-block">Forgot your password?</a>
                        </div>
                        <div class="col-md-6">
                            <button class="btn btn-block btn-primary">Log In</button>
                        </div>
                    </div>
                    </form>
                    <div class="login-or">OR</div>
                    <div class="form-group">
                        <div class="col-md-4">
                            <a href="{% url 'twtlogin' %}"><button class="btn btn-info btn-block btn-twitter"><span class="fa fa-twitter"></span>Twitter</button></a>
                        </div>
                        <div class="col-md-4">
                            <a href="{% url 'fblogin' %}"><button class="btn btn-info btn-block btn-facebook"><span class="fa fa-facebook"></span> Facebook</button></a>
                        </div>
                        <div class="col-md-4">                            
                            <a href="{% url 'gplogin' %}"><button class="btn btn-info btn-block btn-google"><span class="fa fa-google-plus"></span> Google</button></a>
                        </div>
                    </div>
                    <div class="login-subtitle">
                        Don't have an account yet? <a href="/register/">Create an account</a>
                    </div>
                    
                    {% endblock innerbody %}

templates/core/login.html
{% extends "core/base.html" %}
{% load static from staticfiles %}

{% block extra-js %}
        <script type="text/javascript">
        $(function(){
                $('#id_username').attr('placeholder', 'E-mail');
                $('#id_username').attr('class', 'form-control');
                $('#id_password').attr('placeholder', 'Password');
                $('#id_password').attr('class', 'form-control');
        });
        </script>
{% endblock extra-js %}

                    {% block innerbody %}
                    {% if form.non_field_errors %}
                    <div class="form-group has-error">
                        <label class="control-label">{{ form.non_field_errors }}</label>
                    </div>
                    {% endif %}
                    <div class="login-title"><strong>Log In</strong> to your account</div>
                    <form action="" class="form-horizontal" method="post">{% csrf_token %}
                    <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                        <div class="col-md-12">
                            {% if form.username.errors %}
                              <label class="control-label">{{ form.username.errors }}</label>
                            {% endif %}
                            {{ form.username }}
                        </div>
                    </div>
                    <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                        <div class="col-md-12">
                            {% if form.password.errors %}
                              <label class="control-label">{{ form.password.errors }}</label>
                            {% endif %}
                            {{ form.password }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <a href="{% url 'registration' %}" class="btn btn-link btn-block">Register</a>
                        </div>
                        <div class="col-md-6">
                            <button class="btn btn-block btn-primary">Log In</button>
                        </div>
                    </div>
                    </form>
                    <div class="login-or">OR</div>
                    <div class="form-group">
                        <div class="col-md-4">
                            <a href="{% url 'twtlogin' %}"><button class="btn btn-info btn-block btn-twitter"><span class="fa fa-twitter"></span>Twitter</button></a>
                        </div>
                        <div class="col-md-4">
                            <a href="{% url 'fblogin' %}"><button class="btn btn-info btn-block btn-facebook"><span class="fa fa-facebook"></span> Facebook</button></a>
                        </div>
                        <div class="col-md-4">                            
                            <a href="{% url 'gplogin' %}"><button class="btn btn-info btn-block btn-google"><span class="fa fa-google-plus"></span> Google</button></a>
                        </div>
                    </div>
                    <div class="login-subtitle">
                        Don't have an account yet? <a href="#">Create an account</a>
                    </div>
                    
                    {% endblock innerbody %}

templates/core/registration.html
{% extends "core/base.html" %}
{% load static from staticfiles %}

{% block extra-js %}
        <script type="text/javascript">
        $(function(){
                $('#id_name').attr('placeholder', 'Name');
                $('#id_name').attr('class', 'form-control');
                $('#id_email').attr('placeholder', 'E-mail');
                $('#id_email').attr('class', 'form-control');
                $('#id_password').attr('placeholder', 'Password');
                $('#id_password').attr('class', 'form-control');
                $('#id_pwd2').attr('placeholder', 'Password again');
                $('#id_pwd2').attr('class', 'form-control');
        });
        </script>
{% endblock extra-js %}

{% block quote %}
   <div class="blockquote">
       <h4>"If there is no struggle there is no progress... Power concedes nothing without a demand. It never did and it never will.” 
           <footer><cite>Frederick Douglass</cite></footer>
       </h4>
   </div>
{% endblock %}

                    {% block innerbody %}
                    {% if form.non_field_errors %}
                    <div class="form-group has-error">
                        <label class="control-label">{{ form.non_field_errors }}</label>
                    </div>
                    {% endif %}
                    <div class="login-title"><strong>Register</strong> (It's pretty simple)</div>
                    <form action="" class="form-horizontal" method="post">{% csrf_token %}
                    <div class="form-group{% if form.name.errors %} has-error{% endif %}">
                        <div class="col-md-12">
                            {% if form.name.errors %}
                              <label class="control-label">{{ form.name.errors }}</label>
                            {% endif %}
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="form-group{% if form.email.errors %} has-error{% endif %}">
                        <div class="col-md-12">
                            {% if form.email.errors %}
                              <label class="control-label">{{ form.email.errors }}</label>
                            {% endif %}
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                        <div class="col-md-12">
                            {% if form.password.errors %}
                              <label class="control-label">{{ form.password.errors }}</label>
                            {% endif %}
                            {{ form.password }}
                        </div>
                    </div>
                    <div class="form-group{% if form.pwd2.errors %} has-error{% endif %}">
                        <div class="col-md-12">
                            {% if form.pwd2.errors %}
                              <label class="control-label">{{ form.pwd2.errors }}</label>
                            {% endif %}
                            {{ form.pwd2 }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <a href="{% url 'login' %}" class="btn btn-link btn-block">Login</a>
                        </div>
                        <div class="col-md-6">
                            <button class="btn btn-block btn-primary">or Register</button>
                        </div>
                    </div>
                    </form>
                    
                    {% endblock innerbody %}