api/urls.py
from django.conf.urls import url

from api import views


urlpatterns = [
    url(r'^projects/$', views.get_projects),
    url(r'^session/$', views.get_last_session),
    url(r'^start/(?P<id>\d+)/$', views.start_task),
    url(r'^create/$', views.create_task),
    url(r'^update/(?P<id>\d+)/$', views.update_task),
    url(r'^stop/(?P<id>\d+)/$', views.stop_task),
    url(r'^login/$', views.login),
]

tasks/urls.py
from django.conf.urls import url

from tasks import views


urlpatterns = [
    url(r'list/(?P<id>\d+)/$', views.activities, name='task_list'),
    url(r'hrs/(?P<id>\d+)/$', views.work_hours, name='task_work_hours'),
    url(r'summary/$', views.summary, name='task_summary'),
    url(r'days/(?P<id>\d+)/$', views.daily_hours, name='task_daily_hours'),
    url(r'reports/$', views.reports, name='task_reports'),
    url(r'sessions_json/$', views.sessions_json),
    url(r'start/(?P<id>\d+)/$', views.start_task, name='task_start'),
    url(r'continue/(?P<id>\d+)/$', views.continue_task, name='task_continue'),
    url(r'time/(?P<id>\d+)/$', views.time_task, name='task_timing'),
    url(r'sessions/(?P<id>\d+)/$', views.sessions, name='task_sessions'),
    url(r'edit_session/(?P<id>\d+)/$', views.edit_session, name='task_edit_session'),
]

timer/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

#from tasks import views as task_views
from core import views as core_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/$', core_views.dash, name='profile'),
    url(r'^accounts/logout/$',
        auth_views.logout,
        {'next_page': '/accounts/login/'},
        name='logout'),
    url(r'^accounts/login/$',
        auth_views.login,
        {'template_name': 'core/pages-login.html'},
        name='login'),
    url(r'^register/$', core_views.registration, name='registration'),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('profile'))),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

tasks/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Rate(models.Model):
    user = models.ForeignKey(User)
    rate = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __unicode__(self):
        return self.user.username


class Project(models.Model):
    name = models.CharField(max_length=100)
    owner = models.ForeignKey(User)
    started = models.DateTimeField(default=timezone.now)
    url = models.URLField(blank=True, null=True)
    rate = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-started']

    def __unicode__(self):
        return self.name

    @property
    def member_count(self):
        return self.project_members.count()

    @property
    def task_count(self):
        return Task.objects.filter(member__project=self).count()


class Member(models.Model):
    project = models.ForeignKey(Project, related_name='project_members')
    user = models.ForeignKey(User)
    joined = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ('project', 'user')

    def __unicode__(self):
        return self.user.username

    def stop_running_tasks(self):
        TaskSession.objects.filter(
            task__member=self,
            ended__isnull=True
        ).update(ended=timezone.now())

    @property
    def running_tasks(self):
        TaskSession.objects.filter(
            task_member=self, task_ended__isnull=True).count()

    @property
    def total_hours(self):
        start = timezone.now().replace(day=1, hour=0, minute=0, second=0)
        total_seconds = sum([i.duration for i in TaskSession.objects.filter(
            task__member=self, started__gte=start)])
        return total_seconds / 3600.


class Task(models.Model):
    member = models.ForeignKey(Member)
    started = models.DateTimeField()
    activity = models.TextField(null=True, blank=True)
    billable = models.BooleanField(default=True)

    def __unicode__(self):
        return unicode(self.activity)

    @property
    def duration_human(self):
        seconds = self.duration
        hrs = int(seconds)/3600
        mins = (int(seconds) % 3600) / 60
        return '%s hrs %s mins' % (hrs, mins)

    @property
    def duration(self):
        return sum(t.duration for t in self.sessions.all())

    @property
    def session_count(self):
        return self.sessions.count()


class TaskSession(models.Model):
    task = models.ForeignKey(Task, related_name='sessions')
    started = models.DateTimeField(default=timezone.now)
    ended = models.DateTimeField(blank=True, null=True)
    commit = models.CharField(max_length=250, blank=True)

    def __unicode__(self):
        return unicode(self.task)

    @property
    def duration(self):
        if self.ended:
            return (self.ended - self.started).total_seconds()
        else:
            return 0

    @property
    def duration_human(self):
        seconds = self.duration
        hrs = int(seconds)/3600
        mins = (int(seconds) % 3600) / 60
        return '%s hrs %s mins' % (hrs, mins)

    @property
    def commit_url(self):
        return '{}{}'.format(self.task.member.project.url, self.commit)

tasks/forms.py
from django import forms


class TaskForm(forms.Form):
    activity = forms.CharField(
        max_length=250, widget=forms.Textarea(attrs={'rows': "4"}))


class SessionForm(forms.Form):
    hours = forms.IntegerField()
    minutes = forms.IntegerField()
    commit = forms.CharField(
        max_length=250,
        required=False,
        widget=forms.Textarea(attrs={'rows': '3'}))


class DateForm(forms.Form):
    start = forms.DateField()


class DateRangeForm(forms.Form):
    start = forms.DateField()
    end = forms.DateField()

tasks/views.py
from collections import defaultdict

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.utils import timezone
from django.http import JsonResponse
from dateutil import relativedelta

from tasks.models import Task, Project, Member, TaskSession, Rate
from tasks.forms import TaskForm, SessionForm, DateForm, DateRangeForm


def summary(request):
    form = DateRangeForm(request.GET)
    if form.is_valid():
        start = form.cleaned_data['start']
        end = form.cleaned_data['end']
    else:
        start = timezone.now().date()
        end = timezone.now().date()

    sessions = TaskSession.objects.filter(
        started__date__gte=start,
        started__date__lte=end)

    d = defaultdict(int)
    for sess in sessions:
        d[sess.task.member.user.username] += sess.duration

    out = []
    for key, val in d.items():
        try:
            _rate = Rate.objects.get(user__username=key)
            rate = _rate.rate
        except Rate.DoesNotExist:
            rate = 0
        hrs = val/3600.
        amt = hrs * int(rate)
        hrs_fmt = '{:.2f}'.format(hrs)
        amt_fmt = '{:.2f}'.format(amt)
        item = [key, rate, hrs, amt, hrs_fmt, amt_fmt]
        out.append(item)
    #total_hrs = '{:.2f}'.format(sum(d.values()) / 3600.)
    total_hrs = '{:.2f}'.format(sum([i[2] for i in out]))
    total_amt = '{:.2f}'.format(sum([i[3] for i in out]))
    return render(
        request,
        'tasks/summary.html',
        {
            'tasks': out,
            'form': form,
            'total_time': total_hrs,
            'cost': total_amt
        }
    )


def daily_hours(request, id):
    project = get_object_or_404(Project, pk=id)
    sessions = TaskSession.objects.filter(task__member__project=project)

    form = DateForm(request.GET)
    if form.is_valid():
        start = form.cleaned_data['start']
        sessions = sessions.filter(started__date__gte=start)

    d = defaultdict(int)
    for sess in sessions:
        d[sess.started.strftime('%d-%b-%Y')] += sess.duration

    total_hrs = sum(d.values()) / 3600.
    cost = total_hrs * float(project.rate)
    out = [
        (k, '{:.2f}'.format(v/3600.),
            int(v*float(project.rate)/3600)) for k, v in d.items()]
    return render(
        request,
        'tasks/days.html',
        {
            'tasks': out,
            'project': project,
            'form': form,
            'total_time': total_hrs,
            'cost': cost
        }
    )


def work_hours(request, id):
    #import pdb;pdb.set_trace()
    project = get_object_or_404(Project, pk=id)
    tasks = Task.objects.filter(member__project=project)

    form = DateForm(request.GET)

    if form.is_valid():
        start = form.cleaned_data['start']
        tasks = tasks.filter(started__date__gte=start)

    total_time = sum(tsk.duration for tsk in tasks)//(60 * 60)
    cost = int(total_time) * project.rate
    return render(
        request,
        'tasks/hours.html',
        {
            'tasks': tasks,
            'project': project,
            'form': form,
            'total_time': total_time,
            'cost': cost
        }
    )


@login_required
def activities(request, id):
    project = get_object_or_404(Project, pk=id)
    tasks = Task.objects.filter(
        member__user=request.user, member__project=project).order_by('-id')
    return render(
        request, 'tasks/tasks.html', {'tasks': tasks, 'project': project})


@login_required
def start_task(request, id):
    project = get_object_or_404(Project, pk=id)
    member = Member.objects.get(user=request.user, project=project)
    if request.method == 'POST':
        TaskSession.objects.filter(
            task__member__user=request.user,
            ended__isnull=True).update(
            ended=timezone.now())
        form = TaskForm(request.POST)
        if form.is_valid():
            activity = form.cleaned_data['activity']
            task = Task.objects.create(
                member=member, started=timezone.now(), activity=activity)
            #make sure no other task is running
            #member.stop_running_tasks()

            task_session = TaskSession.objects.create(task=task)
            return redirect('task_timing', id=task_session.id)
    else:
        form = TaskForm()
    return render(
        request, 'tasks/new_task.html', {'form': form, 'project': project})


@login_required
def continue_task(request, id):
    task = get_object_or_404(Task, pk=id)
    task_session = TaskSession.objects.create(task=task)
    return redirect('task_timing', id=task_session.id)


@login_required
def time_task(request, id):
    task_session = get_object_or_404(TaskSession, pk=id)
    session_time = (timezone.now() - task_session.started).total_seconds()
    activity_time = task_session.task.duration
    status = request.GET.get('activity_status', '')
    if status == 'pause':
        task_session.ended = timezone.now()
        task_session.save()
    elif status == 'play':
        new_session = TaskSession.objects.create(task=task_session.task)
        return redirect('task_timing', id=new_session.id)
    elif status == 'stop':
        task_session.ended = timezone.now()
        task_session.save()
        return redirect('task_list', id=task_session.task.member.project.id)
    #import pdb;pdb.set_trace()
    #if (timezone.now() - task_session.started).total_seconds > 2:
        #task_session.ended = timezone.now()
        #new_session = TaskSession.objects.create(task=task_session.task)
        #return redirect('task_timing', id=new_session.id)
    return render(
        request,
        'tasks/counting.html',
        {
            'time_spent': session_time + activity_time,
            'task_session': task_session,
            'status': status or 'play',
        }
    )


def sessions(request, id):
    task = get_object_or_404(Task, pk=id)
    return render(
        request,
        'tasks/sessions.html',
        {
            'task_sessions': task.sessions.all(),
            'project_id': task.member.project.id,
            'task': task
        }
    )


def edit_session(request, id):
    session = get_object_or_404(TaskSession, pk=id)
    if not session.ended:
        session.ended = timezone.now()
        session.save()
    total_secs = (session.ended - session.started).total_seconds()
    init_hrs = int(total_secs)/3600
    init_mins = (int(total_secs) % 3600) / 60
    initial_data = {'hours': init_hrs, 'minutes': init_mins}
    if request.method == 'POST':
        form = SessionForm(request.POST, initial=initial_data)
        if form.is_valid():
            hours = form.cleaned_data['hours']
            minutes = form.cleaned_data['minutes']
            timediff = timezone.timedelta(hours=hours, minutes=minutes)
            session.ended = session.started + timediff
            session.commit = form.cleaned_data['commit']
            session.save()
            return redirect('task_sessions', id=session.task.id)
    else:
        form = SessionForm(initial=initial_data)
    return render(
        request,
        'tasks/edit_session.html',
        {
            'form': form,
            'task_session': session
        }
    )


def reports(request):
    return render(request, 'tasks/reports.html', {})


def sessions_json(request):
    date_range = request.GET.get('daterange', 'current')

    users = User.objects.filter(is_active=True)
    #users = defaultdict(list)
    today = timezone.now().date()
    last_month = today + relativedelta.relativedelta(months=-1)
    this_month_start = today + relativedelta.relativedelta(day=1)
    last_month_start = last_month + relativedelta.relativedelta(day=1)
    last_month_end = this_month_start + relativedelta.relativedelta(days=-1)
    if date_range == 'current':
        start = this_month_start
        end = today
    else:
        start = last_month_start
        end = last_month_end
    dates = [start + timezone.timedelta(i) for i in range((end-start).days+1)]
    labels = [dt.strftime('%d %b') for dt in dates]
    print dates

    data = {}
    summary = []
    for usr in users:
        usr_data = []
        sess_dict = defaultdict(int)
        for dt in dates:
            sess_dict[dt] = 0

        for usr_session in TaskSession.objects.filter(
                started__date__gte=start, task__member__user=usr):
            sess_dict[usr_session.started.date()] += usr_session.duration/3600.

        for dt in dates:
            usr_data.append(sess_dict[dt])
        data[usr.username] = usr_data
        summary.append({'name': usr.username, 'time': sum(sess_dict.values())})
    print data
    return JsonResponse({'data': data, 'dates': labels, 'summary': summary})

templates/tasks/counting.html
{% extends 'tasks/form_base.html' %}
{% load static from staticfiles %}

{% block pagetitle %}Payment{% endblock pagetitle %}

{% block extra-js %}
<script type="text/javascript">
$(function(){
	$('.form-control[disabled]').css('color', '#000');
	
	$('#id_activity').addClass('form-control');
    
    var pad_time = function(value){
        if (value < 10){
            return "0" + value;
        } else {
            return "" + value;
        }
    }

    var display_time = function(seconds){
        var hours = Math.floor(seconds/3600);
        var secs_less_hrs = seconds % 3600;
        var minutes = Math.floor(secs_less_hrs/60);
        var seconds = Math.floor(secs_less_hrs % 60);

        $('#id_second').html(pad_time(seconds));
        $('#id_minute').html(pad_time(minutes));
        $('#id_hour').html(pad_time(hours));
    }
    var count = {{ time_spent }};
    display_time(count);

    var func = function(){
        count++;
        display_time(count);
    }
    var current_status = $('#id_status').val();
    if (current_status == 'play'){
        setInterval(func, 1000);
    }
    //setInterval(func, 1000);
});
</script>
{% endblock extra-js %}

	{% block breadcrumb %}
    <!-- START BREADCRUMB -->
    <ul class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li><a href="#">Tasks</a></li>
        <li class="active">Activity</li>
    </ul>
    <!-- END BREADCRUMB -->
	{% endblock breadcrumb %}

{% block midpanel-heading %}
    <h3 class="panel-title">Running Activity</h3>
{% endblock midpanel-heading %}

{% block link %}

{% endblock link %}

{% block pagecontent %}
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-3">
            
        </div>
         <div class="col-md-3">
            <div class="widget widget-danger widget-padding-sm">
                {% comment %}<span id="id_status" class="display: none;">{{ status }}</span>{% endcomment %}
                <input type="hidden"" value="{{ status }}" id="id_status" />
                <div class="widget-big-int">
                    <span id="id_hour">00</span>
                    <span> : </span>
                    <span id="id_minute">00</span>
                    <span> : </span>
                    <span id="id_second">00</span>
                </div>
            </div>
        </div>
         <div class="col-md-3">
           
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading">
                    Running Activity
                </div>
                <div class="panel-body">
                    <div class="col-md-6">
                        <h3>{{ task_session.task.activity }}</h3>
                    </div>
                </div>
            </div>
          
        </div>
        <div class="col-md-6">
            <div class="panel panel-warning">
                <div class="panel-heading">Controls</div>
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" role="form">{% csrf_token %}
                        <div class="form-group">
                            <div class="col-md-6">
                                <div class="btn-group">
                                   
                                    <div class="col-md-4">
                                         {% if status == 'play' or status == '' %}
                                    <a href="{% url 'task_timing' id=task_session.id %}?activity_status=pause" class="btn btn-default">
                                        <i class="fa fa-pause">
                                        </i>
                                    </a>
                                    {% else %}
                                    <a class="btn btn-default"><i class="fa fa-pause"></i></a>
                                    {% endif %}
                                    </div>
                                    
                                   
                                    <div class="col-md-4">
                                         {% if status == 'pause' %}
                                     <a href="{% url 'task_timing' id=task_session.id %}?activity_status=play" class="btn btn-default">
                                        <i class="fa fa-play">
                                        </i>
                                    </a>
                                    {% else %}
                                    <a class="btn btn-default"><i class="fa fa-play"></i></a>
                                    {% endif %}
                                    </div>
                                    
                                    <div class="col-md-4">
                                     <a href="{% url 'task_timing' id=task_session.id %}?activity_status=stop" class="btn btn-default">
                                        <i class="fa fa-stop">
                                        </i>
                                    </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock pagecontent %}

{% block midpanel-body %}
<form action="" class="form-horizontal" method="post">{% csrf_token %}
<div class="form-group{% if form.name.errors %} has-error{% endif %}">
    <label class="control-label col-md-2 col-xs-12">Topic</label>
    <div class="col-md-8 col-xs-12">
        {% if form.name.errors %}
             <label class="control-label">{{ form.name.errors }}</label>
        {% endif %}
        {{ form.name }}
    </div>
</div>

<div class="form-group{% if form.post.errors %} has-error{% endif %}">
    <label class="control-label col-md-2 col-xs-12">Post</label>
    <div class="col-md-8 col-xs-12">
        {% if form.post.errors %}
             <label class="control-label">{{ form.post.errors }}</label>
        {% endif %}
        {{ form.post }}
    </div>
</div>
<div class="form-group">
    <div class="col-md-2"></div>
    <div class="col-md-6">
        <button class="btn btn-block btn-primary">Post</button>
    </div>
</div>
</form>
{% endblock midpanel-body %}

{% block midpanel-footer %}
{% endblock midpanel-footer %}

templates/tasks/summary.html
{% extends 'tasks/form_base.html' %}
{% load static from staticfiles %}

{% block pagetitle %}Work Summary{% endblock pagetitle %}

{% block breadcrumb %}
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li class="active">Summary</li>
</ul>
<!-- END BREADCRUMB -->
{% endblock breadcrumb %}

{% block links %}
{% endblock links %}

{% block pagecontent %}
<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <!-- START WIDGETS -->
    <div class="row">

        <div class="col-md-3">

            <!-- START WIDGET MESSAGES -->
            <div class="widget widget-default widget-item-icon">
                <div class="widget-item-left">
                    <span class="fa fa-clock-o"></span>
                </div>
                <div class="widget-data">
                    <div class="widget-int num-count">{{ total_time }} hrs</div>
                    <div class="widget-title">Time Spent</div>
                    <div class="widget-subtitle">Total time spent till date</div>
                </div>
                <div class="widget-controls">
                    <a href="#" class="widget-control-right widget-remove" data-toggle="tooltip" data-placement="top"
                        title="Remove Widget"><span class="fa fa-times"></span></a>
                </div>
            </div>
            <!-- END WIDGET MESSAGES -->

        </div>
        {% comment %} <div class="col-md-3">
            <!-- START WIDGET REGISTRED -->
            <div class="widget widget-default widget-item-icon">
                <div class="widget-item-left">
                    <span class="fa fa-user"></span>
                </div>
                <div class="widget-data">
                    <div class="widget-int num-count">{{project.rate}} / hr</div>
                    <div class="widget-title">Rate</div>
                    <div class="widget-subtitle">Project Hourly Rate!</div>
                </div>
                <div class="widget-controls">
                    <a href="#" class="widget-control-right widget-remove" data-toggle="tooltip" data-placement="top"
                        title="Remove Widget"><span class="fa fa-times"></span></a>
                </div>
            </div>
            <!-- END WIDGET REGISTRED -->

        </div> {% endcomment %}
        <div class="col-md-3">

            <!-- START WIDGET CLOCK -->
            <div class="widget widget-success widget-padding-sm">
                <div class="widget-big-int">&#8358; {{cost}}</div>
                <div class="widget-title">Cost</div>
                <div class="widget-subtitle">Cost of Work till date</div>
                <div class="widget-controls">
                    <a href="#" class="widget-control-right widget-remove" data-toggle="tooltip" data-placement="left"
                        title="Remove Widget"><span class="fa fa-times"></span></a>
                </div>
            </div>
            <!-- END WIDGET CLOCK -->

        </div>
    </div>
    <!-- END WIDGETS -->

    <div class="row">
        <div class="col-md-12">

            <!-- START LINE CHART -->
            <!-- START BASIC TABLE SAMPLE -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-8">
                                <h3 class="panel-title">Summary of Tasks </h3>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form">
                                <form action="." method="GET" class="form-inline">
                                    <div class="input-group date" data-provide="datepicker">
                                        {{ form.start }}
                                        <div class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </div>
                                    </div>
                                     <div class="input-group date" data-provide="datepicker">
                                        {{ form.end }}
                                        <div class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </div>
                                    </div>
                                    <button class="btn btn-success search-button"> <i class="fa fa-search"></i> Search</button>
                                </form>
                            </div>
                        </div>

                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Person</th>
                                        <th>Rate</th>
                                        <th>Hours</th>
                                        <th>Amount</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for task in tasks %}
                                    <tr>
                                        <td>{{ task.0 }}</td>
                                        <td>{{ task.1 }}</td>
                                        <td>{{ task.4 }}</td>
                                        <td>{{ task.5 }}</td>
                                    </tr>
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- END LINE CHART -->

            </div>
        </div>
    </div>
    <!-- PAGE CONTENT WRAPPER -->
    {% endblock pagecontent %}




    {% block extra-footer-js %}

    <!-- START THIS PAGE PLUGINS--> {% comment %}
    <script type="text/javascript" src="{% static 'js/plugins/icheck/icheck.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/scrolltotop/scrolltopcontrol.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/plugins/morris/raphael-min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/morris/morris.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/rickshaw/d3.v3.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/rickshaw/rickshaw.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/bootstrap/bootstrap-datepicker.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/owl/owl.carousel.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/plugins/moment.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/plugins/daterangepicker/daterangepicker.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dash_chart.js' %}"></script>
    {% endcomment %}
    <!-- END THIS PAGE PLUGINS-->
    <script type="text/javascript" src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
    <script type="text/javascript">
        $('#id_start').addClass('form-control')
        $('.date').datepicker({
            autoclose: true
        });
        $('#id_end').addClass('form-control')
        $('.date').datepicker({
            autoclose: true
        });
    </script>

    {% endblock extra-footer-js %}